name: autoint
channels:
  - conda-forge
  - defaults
dependencies:
  - configargparse=1.4=pyhd3eb1b0_0
  - networkx=2.5=py_0
  - numpy=1.19.2
  - pillow=8.1.2
  - pip=21.0.1
  - python=3.7.10
  - scikit-image
  - scikit-video=1.1.11=pyh24bf2e0_0
  - tensorboard=2.4.0=pyhc547734_0
  - tqdm=4.59.0=pyhd3eb1b0_1
  - pip:
    - colour==0.1.5
    - moviepy==1.0.3
    - torch==1.5.1
    - torchmeta==1.4.6
    - torchvision==0.6.1
